site_name: Buggg的小屋

nav:
  - 主页: home.md
  - 概率论与数理统计:
    - 简介: probability/0.md
    - 样本空间 随机事件: probability/1.md

repo_url: https://github.com/1216105249/wiki

theme:
  name: material
  language: zh
  palette:
    - scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: 切换亮色模式
    - scheme: slate
      primary: blue grey
      accent: blue
      toggle:
        icon: material/weather-night
        name: 切换暗色模式
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - search.share

markdown_extensions:
  - smarty
  - toc:
      permalink: true
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  

extra_javascript:
  - 'js/extra.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/1216105249
      name: Github
    - icon: fontawesome/solid/paper-plane
      link: mailto:<1216105249@qq.com>
      name: 邮箱

copyright: Copyright &copy; 2020 - 2021 Buggg的小屋
