site_name: Buggg的小屋

nav:
  - 主页: 
    - 主页: 主页/0主页.md
  - 概率论与数理统计:
    - 简介: 概率论与数理统计/0简介.md
    - 样本空间 随机事件: 概率论与数理统计/1样本空间 随机事件.md

theme:
  name: material
  language: zh
  palette:
    - scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: 切换亮色模式
    - scheme: slate
      primary: blue grey
      accent: blue
      toggle:
        icon: material/weather-night
        name: 切换暗色模式
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.share

markdown_extensions:
  - toc:
      permalink: true

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/1216105249
      name: Github
    - icon: fontawesome/solid/paper-plane
      link: mailto:<1216105249@qq.com>
      name: 邮箱

copyright: Copyright &copy; 2020 - 2021 Buggg的小屋

repo_url: https://github.com/1216105249/wiki